version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "slimreaper35"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    assignees:
      - "slimreaper35"
    schedule:
      interval: "monthly"
    groups:
      python-packages:
        patterns:
          - "*"
