default_stages: [ pre-commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: pretty-format-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt
        args: [ --stdout ]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.1.0"
    hooks:
      - id: pyproject-fmt
        args: [ --stdout, --indent=4 ]
