name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nox_env:
          - ruff
          - ty

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install nox uv
      - name: Run '${{ matrix.nox_env }}' with nox
        run: nox -s ${{ matrix.nox_env }}

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install nox uv
      - name: Run tests with nox
        run: nox -s pytest
      - name: Upload coverage report
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
