name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nox_env:
          - ruff
          - mypy

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install nox
      - name: Test '${{ matrix.nox_env }}' with nox
        run: nox -e ${{ matrix.nox_env }}

  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install nox
          pip install coverage
      - name: Test with nox
        run: nox -e pytest
      - name: Upload coverage report
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
